### ISSUE TITLE
Build out the Priority Scoring Feature

### ISSUE THREAD

**Issue by smcalilly** [datamade/ccfp-asset-dashboard#18]
Here is the wireframe: https://projects.invisionapp.com/share/7FZ8N9VC4AT#/screens/439986471

This should be accessible from the project detail page.

**Comment by smcalilly** [comment]
@fgregg I need some help on how to reconcile the wireframe and models.

The wireframe suggests that you can add a project to a project. See the "add project or place" button on this screen: https://projects.invisionapp.com/share/7FZ8N9VC4AT#/screens/439986470.

Based on user research, it seems like they will sometimes group multiple, similar projects into one project in order to get funding for all of the projects. For example, from my understanding, they'll group roofing repairs for several buildings into one "project", even though each building's repair project was originally its own separate "project". 

I'm guessing that this wireframe is trying to appease that requirement. [The "priority scoring" wireframe](https://projects.invisionapp.com/share/7FZ8N9VC4AT#/screens/439986471) appears to be doing the same thing, as evidenced by the table with multiple projects.

As the models currently stand, I don't understand how this might work from a code or UI or database perspective. There's some way we'll have to do this, but how?

**Comment by fgregg** [comment]
Let's skip the "add project to project." 

They might really need a way of grouping project together, but i don't think that the "project" is the right concept for that.

**Comment by smcalilly** [comment]
@fgregg I’m writing tests for PR #20 and found a bug. Whenever the code creates a new Project, it doesn’t create an associated ProjectCategory. Is that something that we’d want to include on the initial form, where a user creates a new project? If a ProjectCategory is something like "capital improvement" or "maintenance" etc, it might make sense to include that in the [create form for a project](https://projects.invisionapp.com/share/7FZ8N9VC4AT#/screens/438121592). 

Which do you think is the best choice? A project category can be either: 
1. created manually by a user when a new Project is created
2. created programmatically with default values when the Project is created

We have an issue for getting the ProjectCategory data from Garret here: #13, so I can create some dummy data for this in the meantime.

**Comment by smcalilly** [comment]
Ignore my above comment. A project category would be created via the admin interface and not by an end user. For development fixtures, I'm using the project categories from [the csv of the CIP](https://github.com/datamade/ccfp-asset-dashboard/blob/master/raw/2021CIPTablesDRAFT10.28.2020updated_GW_clean.csv).

**Comment by smcalilly** [comment]
Closed with #20.
