### ISSUE TITLE
Nested forms for the Project model detail view

### ISSUE THREAD

**Issue by smcalilly** [datamade/ccfp-asset-dashboard#21]
A Project detail view needs different forms associated with it. [Based on this wireframe](https://projects.invisionapp.com/share/7FZ8N9VC4AT#/screens/439986470), we need to finish building out the form:
- [x] Project
- [x] ProjectScore (see #18)
<s>- [ ] ProjectFinances</s> (we don't need this)
<s> - [ ] Places (not sure the model?)</s> won't be in the model
- [x] Section 
- [x] ProjectCategory
- [x] various political districts
- [x] Zone
- [x] total budget for a project
- [x] Phase (currently a boolean value)

We also need to setup the admin section so that an admin can create some admin data. Some of these are mentioned in issue #13, but here's a more comprehensive list:
- [x] ScoreWeight

@fgregg am I missing anything here?

**Comment by fgregg** [comment]
* project category
* political districts
* zone

all need to be in the form too.

**Comment by smcalilly** [comment]
Before closing:
1. See note in PR #23 about the project categories.
2. I added the score weight as a fixture. The admins can update it however they want. If they add another score weight, the new score weight won't be added to the calculation. It will only use the one from the fixture. Need to communicate this for admin training.

**Comment by smcalilly** [comment]
From Garret's notes about this form

Categories to add:

Estimated Bid Quarter. 
Values: Q1, Q2, Q3, Q4

Project Phase. 
Values: Phase 1, Phase 2, Phase 3 Engineering. Phase 3 Construction, Feasibility, Design, Construction
